"use client"

import Image from "next/image"
import Link from "next/link"
import { Clock, Mail, MapPin, MessageSquare, Phone, ArrowRight, BookOpen, ExternalLink } from "lucide-react"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { PageHero, Reveal, SectionLabel } from "@/components/editorial"

const contactInfo = [
  { icon: Phone, title: "Direct Lines", details: ["+263 78 605 3315", "+263 71 322 5707"], action: "Call or WhatsApp for enquiries" },
  { icon: Mail, title: "Official Email", details: ["johnariphiosd@gmail.com", "principal@globedk.co.zw"], action: "We aim to respond within 24 hours" },
  { icon: MapPin, title: "Tutoring Center", details: ["Epworth, Harare", "Zimbabwe"], action: "Physical and online lessons available" },
  { icon: Clock, title: "School & Lesson Schedule", details: ["School Hours: 8:00 AM - 4:00 PM", "Lessons: Monday - Friday"], action: "Flexible learning arrangements available" },
]

const subjects = ["Mathematics", "English Language", "Combined Science", "Physics", "Chemistry", "Biology", "Computer Science", "Geography", "History", "Heritage Studies", "Commerce", "Principles of Accounts", "Pure Mathematics", "Statistics", "Business Studies", "Economics"]

function whatsAppUrl(number: string) {
  const message = "Hello GlobeDk Elite Academy. I am interested in your tutoring services and would like to know more about lessons, subjects, fees and class schedules. I would also like to know how I can enrol. Thank you."
  return `https://wa.me/${number}?text=${encodeURIComponent(message)}`
}

export default function ContactPage() {
  return (
    <div className="homepage-shell min-h-screen overflow-x-clip bg-[#f4f1ea] text-[#14263d]">
      <Navigation />
      <main>
        <PageHero number="01" eyebrow="Start a conversation" title={<>Let’s plan the learner’s <span className="text-[#e3a56f]">next step.</span></>} description={<>Hi, I'm <strong className="font-semibold text-white">John Ariphios Daka</strong>, Founder and Principal of GlobeDk Elite Academy. Whether you're a student, parent, guardian, or teacher, feel free to reach out for enrolment, lesson schedules, subject enquiries, academic support, or partnership opportunities.</>} sideLabel="Admissions · Lesson enquiries · Academic support" />

        <section className="bg-[#f4f1ea] py-20 sm:py-28"><div className="container"><Reveal><div className="grid gap-10 rounded-[1.75rem] border border-[#d9d3c8] bg-white/35 p-6 sm:p-10 lg:grid-cols-[0.55fr_1.45fr] lg:items-center"><div className="relative mx-auto aspect-square w-full max-w-xs overflow-hidden rounded-[1.75rem] bg-[#10243d]"><Image src="/image.jpg" alt="GlobeDk Elite Academy lessons" fill className="object-cover" sizes="(min-width: 1024px) 22vw, 90vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#0b1d33]/70 to-transparent" /><p className="absolute bottom-5 left-5 text-[10px] font-bold uppercase tracking-[0.2em] text-[#e3a56f]">GlobeDk / Admissions</p></div><div><SectionLabel number="02">A direct line to the academy</SectionLabel><h2 className="mt-6 font-serif text-4xl leading-[0.98] tracking-[-0.04em] sm:text-5xl">Bring us the question. We’ll help find the route.</h2><p className="mt-6 max-w-2xl text-base leading-relaxed text-[#526071]">GlobeDk Elite Academy provides academic support for O-Level and A-Level learners through physical lessons, online lessons, homeschooling, one-on-one tutoring, revision, homework assistance, and examination preparation.</p><p className="mt-4 max-w-2xl text-base leading-relaxed text-[#526071]">We support learners across a wide range of Arts, Commercial, Science, and Technology subjects for both ZIMSEC and Cambridge curricula.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild className="w-full rounded-full bg-[#10243d] text-white hover:bg-[#193653] sm:w-auto"><a href={whatsAppUrl("263786053315")} target="_blank" rel="noopener noreferrer">Message on WhatsApp <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" /></a></Button><Button asChild variant="outline" className="w-full rounded-full border-[#d9d3c8] sm:w-auto"><a href="mailto:principal@globedk.co.zw">Email the principal</a></Button></div></div></div></Reveal></div></section>

        <section className="bg-[#eae4d9] py-16 sm:py-20"><div className="container"><div className="grid gap-x-8 sm:grid-cols-2 lg:grid-cols-4">{contactInfo.map(({ icon: Icon, title, details, action }, index) => <Reveal key={title} delay={index * 0.06} className="border-t border-[#c9c1b4] py-6"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.2em] text-[#b15d2b]">0{index + 1}</span><Icon className="h-5 w-5 text-[#b15d2b]" aria-hidden="true" /></div><h3 className="mt-8 font-serif text-2xl tracking-[-0.03em]">{title}</h3><div className="mt-4 space-y-1 text-sm leading-relaxed text-[#526071]">{details.map((detail) => <p key={detail}>{detail}</p>)}</div><p className="mt-5 text-xs font-semibold leading-relaxed text-[#b15d2b]">{action}</p></Reveal>)}</div></div></section>

        <section className="bg-[#10243d] py-20 text-[#f8f4eb] sm:py-28"><div className="container"><div className="grid gap-12 lg:grid-cols-[0.6fr_1.4fr] lg:gap-24"><Reveal><SectionLabel number="03" light>Find your subject</SectionLabel><h2 className="mt-6 max-w-sm font-serif text-4xl leading-tight tracking-[-0.04em] sm:text-5xl">A clear question makes the first step easier.</h2><p className="mt-6 max-w-sm text-base leading-relaxed text-white/60">GlobeDk Elite Academy provides tutoring across a wide range of subjects for O-Level and A-Level learners. Our subjects cover Arts, Commercials, Sciences, and Technology.</p><Button asChild variant="outline" className="mt-8 rounded-full border-white/25 bg-transparent text-white hover:bg-white/10"><Link href="/subjects">View all subjects <ExternalLink className="ml-2 h-4 w-4" aria-hidden="true" /></Link></Button></Reveal><Reveal delay={0.1}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{subjects.map((subject, index) => <Link key={subject} href={`/subjects#${subject.toLowerCase().replaceAll(" ", "-")}`} className="group flex items-center justify-between border-b border-white/15 py-3 text-sm text-white/70 transition-colors hover:text-white"><span><span className="mr-3 text-[10px] font-bold text-[#e3a56f]">{String(index + 1).padStart(2, "0")}</span>{subject}</span><ArrowRight className="h-3.5 w-3.5 text-[#e3a56f] opacity-0 transition-all group-hover:translate-x-1 group-hover:opacity-100" aria-hidden="true" /></Link>)}</div></Reveal></div></div></section>

        <section className="bg-[#f4f1ea] py-20 sm:py-28"><div className="container"><Reveal><div className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-stretch"><div className="rounded-[1.75rem] bg-[#d87a3f] p-6 text-[#10243d] sm:p-9"><SectionLabel number="04">Chat with GlobeDk</SectionLabel><div className="mt-8 flex h-12 w-12 items-center justify-center rounded-full bg-[#10243d] text-[#e3a56f]"><MessageSquare className="h-5 w-5" aria-hidden="true" /></div><h2 className="mt-7 font-serif text-4xl leading-[0.98] tracking-[-0.04em] sm:text-5xl">Speak directly with our Senior Tutor.</h2><p className="mt-5 max-w-lg text-base leading-relaxed text-[#10243d]/70">Have a question about subjects, enrolment, lesson schedules, online classes, physical lessons, or examination preparation? Send us a message on WhatsApp.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild className="w-full rounded-full bg-[#10243d] text-white hover:bg-[#193653] sm:w-auto"><a href={whatsAppUrl("263786053315")} target="_blank" rel="noopener noreferrer">WhatsApp: +263 78 605 3315</a></Button><Button asChild variant="outline" className="w-full rounded-full border-[#10243d]/35 bg-transparent text-[#10243d] hover:bg-[#10243d]/10 sm:w-auto"><a href={whatsAppUrl("263713225707")} target="_blank" rel="noopener noreferrer">+263 71 322 5707</a></Button></div></div><div className="rounded-[1.75rem] border border-[#d9d3c8] bg-[#eae4d9] p-6 sm:p-9"><SectionLabel number="05">Learning schedule</SectionLabel><h2 className="mt-8 font-serif text-4xl leading-[0.98] tracking-[-0.04em] sm:text-5xl">Flexible academic support designed around the learner.</h2><div className="mt-8 space-y-5">{[{ icon: Clock, title: "School Hours", text: <>School operates from <strong>8:00 AM to 4:00 PM</strong>.</> }, { icon: BookOpen, title: "Lessons", text: <>Lessons are conducted from <strong>Monday to Friday</strong>, with arrangements available for different learning programmes.</> }].map(({ icon: Icon, title, text }) => <div key={title} className="border-t border-[#c9c1b4] pt-5"><div className="flex items-center gap-3"><Icon className="h-5 w-5 text-[#b15d2b]" aria-hidden="true" /><h3 className="font-semibold">{title}</h3></div><p className="mt-3 text-sm leading-relaxed text-[#526071]">{text}</p></div>)}</div><p className="mt-7 text-sm leading-relaxed text-[#526071]">Contact us to confirm the timetable, subject availability, programme, and preferred learning format.</p></div></div></Reveal></div></section>

        <section className="bg-[#eae4d9] py-20 sm:py-28"><div className="container"><Reveal><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionLabel number="06">Visit the academy</SectionLabel><h2 className="mt-5 font-serif text-4xl tracking-[-0.04em] sm:text-5xl">Find GlobeDk Elite Academy.</h2></div><p className="max-w-md text-sm leading-relaxed text-[#526071]">Visit GlobeDk Elite Academy in Epworth, Harare, Zimbabwe.</p></div><div className="overflow-hidden rounded-[1.75rem] border border-[#c9c1b4] bg-white shadow-[0_18px_45px_rgba(20,38,61,.08)]"><div className="aspect-video"><iframe title="GlobeDk Elite Academy - Google Maps" src="https://www.google.com/maps?q=GlobeDk%20Elite%20Academy%2C%20Harare%2C%20Zimbabwe&output=embed" width="100%" height="100%" style={{ border: 0 }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div><a href="https://www.google.com/maps/search/?api=1&query=GlobeDk%20Elite%20Academy%2C%20Harare%2C%20Zimbabwe" target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[#b15d2b] hover:underline"><MapPin className="h-4 w-4" aria-hidden="true" />Open GlobeDk Elite Academy in Google Maps</a></Reveal></div></section>

        <section className="bg-[#0b1d33] py-20 text-white sm:py-28"><div className="container"><Reveal><SectionLabel number="07" light>Make an enquiry</SectionLabel><div className="mt-6 flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><h2 className="max-w-3xl font-serif text-5xl leading-[0.95] tracking-[-0.05em] sm:text-7xl">The right support can change the whole term.</h2><Button asChild size="lg" className="w-full rounded-full bg-[#d87a3f] px-7 text-[#10243d] hover:bg-[#e08a51] sm:w-auto"><a href={whatsAppUrl("263786053315")} target="_blank" rel="noopener noreferrer">Start a conversation <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" /></a></Button></div></Reveal></div></section>
      </main>
      <Footer />
    </div>
  )
}
